<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["screen", "Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Edit screen
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "screen/save",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldArea" class="col-sm-2 control-label">Area</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["area", "size" => 30, "class" => "form-control", "id" => "fieldArea"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldFloor" class="col-sm-2 control-label">Floor</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["floor", "type" => "number", "class" => "form-control", "id" => "fieldFloor"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldRecliner" class="col-sm-2 control-label">Recliner</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["recliner", "type" => "number", "class" => "form-control", "id" => "fieldRecliner"]) ?>
    </div>
</div>


<?php echo $this->tag->hiddenField("id") ?>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
