<?php echo $this->getContent(); ?>
<?php
    echo $this->tag->form(["ticket/placeOrder","autocomplete" => "off", "class" => "form-horizontal"]);
?>
<H2>Place Order</h2>
<table class="table table-condensed table-bordered">
	<thead>
		<tr><th>Id</th><th>Name</th><th>Description</th><th>Price</th><th>Quantity</th></tr></thead>
	<tbody>
	<?php $ttlCost=0; $ttlQty=0;?>
	<?php foreach ($lineitems as $lineitem): ?>
		<?php $ticket=$lineitem['ticket']; ?>	 
		<tr>
			<td><input size="3" style="border:none" type="text" name="ticketid[]" readonly value="<?php echo $ticket->getId()?>"></td>
			<td><?php echo $ticket->getName() ?></td>
			<td><?php echo $ticket->getDescription() ?></td>
			<td><div class="price"><?php echo $ticket->getPrice() ?></div></td>
			<td>
				<input size="3" style="border:none" class="qty" type="text" name="quantity[]" readonly value="<?php echo $lineitem['qty'] ?>">
			</td>
			<td>
				<button type="button" class="btn btn-default add"><span class="glyphicon glyphicon-plus"/></button>
				<button type="button" class="btn btn-default subtract"><span class="glyphicon glyphicon-minus"/></button>
				<button type="button" class="btn btn-default value="remove" onClick="$(this).closest('tr').remove();"><span class="glyphicon glyphicon-remove"/></button>
			</td>
			<?php
				$ttlQty = $ttlQty + $lineitem['qty'];
				$ttlCost = $ttlCost + ($ticket->getPrice()*$lineitem['qty']);	
			?>
		</tr>
	<?php endforeach; ?>
	
	</tbody>
</table>
<button type="submit" class="btn btn-primary">Submit</button>
</form>