<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["customer", "Go Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Create customer
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "user/create",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldFirstname" class="col-sm-2 control-label">Firstname</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["firstname", "size" => 30, "class" => "form-control", "id" => "fieldFirstname"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldSurname" class="col-sm-2 control-label">Surname</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["surname", "size" => 30, "class" => "form-control", "id" => "fieldSurname"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldMembertype" class="col-sm-2 control-label">Membertype</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["membertype", "size" => 30, "class" => "form-control", "id" => "fieldMembertype"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDateofbirth" class="col-sm-2 control-label">Dateofbirth</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["dateofbirth", "type" => "date", "class" => "form-control", "id" => "fieldDateofbirth"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldAddress" class="col-sm-2 control-label">Address</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["address", "size" => 30, "class" => "form-control", "id" => "fieldAddress"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
