<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["customer/index", "Go Back"]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["customer/new", "Create "]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Id</th>
            <th>Firstname</th>
            <th>Surname</th>
            <th>Membertype</th>
            <th>Dateofbirth</th>
            <th>Address</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $customer): ?>
            <tr>
                <td><?php echo $customer->id ?></td>
            <td><?php echo $customer->firstname ?></td>
            <td><?php echo $customer->surname ?></td>
            <td><?php echo $customer->membertype ?></td>
            <td><?php echo $customer->dateofbirth ?></td>
            <td><?php echo $customer->address ?></td>

                <td><?php echo $this->tag->linkTo(["customer/edit/" . $customer->id, "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["customer/delete/" . $customer->id, "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("customer/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("customer/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("customer/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("customer/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
