<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["booking", "Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Edit booking
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "booking/save",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldBookingdate" class="col-sm-2 control-label">Bookingdate</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["bookingdate", "type" => "date", "class" => "form-control", "id" => "fieldBookingdate"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldStarttime" class="col-sm-2 control-label">Starttime</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["starttime", "size" => 30, "class" => "form-control", "id" => "fieldStarttime"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldEndtime" class="col-sm-2 control-label">Endtime</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["endtime", "size" => 30, "class" => "form-control", "id" => "fieldEndtime"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCustomerid" class="col-sm-2 control-label">Customerid</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["customerid", "type" => "number", "class" => "form-control", "id" => "fieldCustomerid"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldScreenid" class="col-sm-2 control-label">Screenid</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["screenid", "type" => "number", "class" => "form-control", "id" => "fieldScreenid"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPrice" class="col-sm-2 control-label">Price</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["price", "type" => "number", "class" => "form-control", "id" => "fieldPrice"]) ?>
    </div>
</div>


<?php echo $this->tag->hiddenField("id") ?>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
