<!DOCTYPE html>
<html lang="en">
<head>
  <!-- Theme Made By www.w3schools.com - No Copyright -->
  <title>Bootstrap Theme The Band</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" type="text/css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <style>
  .navbar {
      font-family: Montserrat, sans-serif;
      margin-bottom: 0;
      background-color: #2d2d30;
      border: 0;
      font-size: 11px !important;
      letter-spacing: 4px;
      opacity: 0.9;
  }
  .navbar li a, .navbar .navbar-brand { 
      color: #d5d5d5 !important;
  }
  .navbar-nav li a:hover {
      color: #fff !important;
  }
  .navbar-nav li.active a {
      color: #fff !important;
      background-color: #29292c !important;
  }
  .navbar-default .navbar-toggle {
      border-color: transparent;
  }
  .open .dropdown-toggle {
      color: #fff;
      background-color: #555 !important;
  }
  .dropdown-menu li a {
      color: #000 !important;
  }
  .dropdown-menu li a:hover {
      background-color: red !important;
  
  </style>
</head>
<body id="myPage" data-spy="scroll" data-target=".navbar" data-offset="50">

<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <a class="navbar-brand" href="#myPage">Local Cinema</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#myPage">HOME</a></li>
        <li><a href="/cinema/user/new">Booking</a></li>
		
       <ul class="nav navbar-nav navbar-right">
      <li><a href="/cinema/user/new"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
      <li><a href="/cinema/user/login"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
	  <form class="navbar-form navbar-left" action="/cinema/user/new">
        </li>
      </ul>
    </div>
  </div>
</nav>

<div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
      <div class="item active">
        <img src="/cinema/public/img/q1.jpg" alt="New York" width="1200" height="700">
        <div class="carousel-caption">
          <h3>A quiet Place</h3>
          <p>Watch today</p>
        </div>      
      </div>

      <div class="item">
        <img src="/cinema/public/img/i10.jpg" alt="Chicago" width="1200" height="700">
        <div class="carousel-caption">
          <h3>Infinity war</h3>
          <p>Can all beat one?, see it now.</p>
        </div>      
      </div>
    
      <div class="item">
        <img src="/cinema/public/img/R7.jpg" alt="Los Angeles" width="1200" height="700">
        <div class="carousel-caption">
          <h3>Rampage</h3>
          <p>Mass destruction an old passed is remade</p>
        </div>      
      </div>
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
</div>



<!-- Container (TOUR Section) -->
<div id="tour" class="bg-1">
  <div class="container">
    <h3 class="text-center">Whats on</h3>
    <p class="text-center">Busy times.<br> Remember to book your tickets!</p>
    <ul class="list-group">
      <li class="list-group-item">April <span class="label label-danger">really busy!</span></li>
      <li class="list-group-item">May <span class="label label-primary">calm period</span></li> 
	    <li class="list-group-item">June <span class="label label-primary">calm period</span></li>

    </ul>
    
    <div class="row text-center">
      <div class="col-sm-4">
        <div class="thumbnail">
          <img src="/cinema/public/img/infinity.jpg" alt="war" width="400" height="300">
          <p><strong>Infinity War</strong></p>
          <p>In cinemas now!</p>
		  <button class="btn" data-toggle="modal" data-target="#myModal">Buy Tickets</button>
        </div>
      </div>
      <div class="col-sm-4">
        <div class="thumbnail">
          <img src="/cinema/public/img/q2.jpg" alt="quiet" width="400" height="300">
          <p><strong>A quiet place</strong></p>
          <p>April 2018</p>
          <button class="btn" data-toggle="modal" data-target="#myModal">Buy Tickets</button>
        </div>
      </div>
      <div class="col-sm-4">
        <div class="thumbnail">
          <img src="/cinema/public/img/rampage.jpg" alt="Rampage" width="400" height="300">
          <p><strong>Rampage</strong></p>
          <p>April 2018</p>
          <button class="btn-facebook" data-toggle="modal" data-target="#myModal">Buy Tickets</button>
        </div>
      </div>
    </div>
  </div>
  
  <div class="row text-center">
      <div class="col-sm-4">
        <div class="thumbnail">
          <img src="/cinema/public/img/dp.jpg" alt="deadpool" width="400" height="300">
          <p><strong>DeadPool Two</strong></p>
          <p>In cinemas now!</p>
          <button class="btn" data-toggle="modal" data-target="#mymodal">Buy Tickets</button>
        </div>
      </div>
      <div class="col-sm-4">
        <div class="thumbnail">
          <img src="/cinema/public/img/jw.jpg" alt="jworld" width="400" height="300">
          <p><strong>Jurassic World Fallen Kingdom</strong></p>
          <p>April 2018</p>
          <button class="btn" data-toggle="modal" data-target="#myModal">Buy Tickets</button>
        </div>
      </div>
      <div class="col-sm-4">
        <div class="thumbnail">
          <img src="/cinema/public/img/pr.jpg" alt="Peter" width="400" height="300">
          <p><strong>Peter rabbit</strong></p>
          <p>May 2018</p>
          <button class="btn" data-toggle="modal" data-target="#myModal">Buy Tickets</button>
        </div>
      </div>
    </div>
  </div>
  
    <div class="row text-center">
      <div class="col-sm-4">
        <div class="thumbnail">
          <img src="/cinema/public/img/simon.jpg" alt="simon" width="400" height="300">
          <p><strong>Love simon</strong></p>
          <p>In cinemas now!</p>
          <button class="btn" data-toggle="modal" data-target="#mymodal">Buy Tickets</button>
        </div>
      </div>
      <div class="col-sm-4">
        <div class="thumbnail">
          <img src="/cinema/public/img/sg.jpg" alt="jworld" width="400" height="300">
          <p><strong>Sherlock Gnomes</strong></p>
          <p>May 2018</p>
          <button class="btn" data-toggle="modal" data-target="#myModal">Coming soon</button>
        </div>
      </div>
      <div class="col-sm-4">
        <div class="thumbnail">
          <img src="/cinema/public/img/rp1.jpg" alt="Peter" width="400" height="300">
          <p><strong>Ready Player one</strong></p>
          <p>May 2018</p>
          <button class="btn" data-toggle="modal" data-target="#myModal">Buy Tickets</button>
        </div>
      </div>
    </div>
  </div>
  
  <!-- Modal -->
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">×</button>
          <h4><span class="glyphicon glyphicon-lock"></span> Sign up </h4>
        </div>
        <div class="modal-body">
           You are halfway there please sign up or log in to take advantage of our order ticket online
		  <div class="progress">
		  <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="50"aria-valuemin="0" aria-valuemax="100" style="width:50%">
  </div>
</div>
        </div>
        <div class="modal-footer">
          <button type="submit" class="btn btn-danger btn-default pull-left" data-dismiss="modal">
            <span class="glyphicon glyphicon-remove"></span> Cancel
          </button>
          <p>Need <a href="#">help?</a></p>
        </div>
      </div>
    </div>
  </div>
</div>


<script>
$(document).ready(function(){
  // Initialize Tooltip
  $('[data-toggle="tooltip"]').tooltip(); 
  
  // Add smooth scrolling to all links in navbar + footer link
  $(".navbar a, footer a[href='#myPage']").on('click', function(event) {

    // Make sure this.hash has a value before overriding default behavior
    if (this.hash !== "") {

      // Prevent default anchor click behavior
      event.preventDefault();

      // Store hash
      var hash = this.hash;

      // Using jQuery's animate() method to add smooth page scroll
      // The optional number (900) specifies the number of milliseconds it takes to scroll to the specified area
      $('html, body').animate({
        scrollTop: $(hash).offset().top
      }, 900, function(){
   
        // Add hash (#) to URL when done scrolling (default click behavior)
        window.location.hash = hash;
      });
    } // End if
  });
})
</script>

</body>
</html>