<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <title>Phalcon PHP Framework</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <link rel="shortcut icon" type="image/x-icon" href="<?php echo $this->url->get('img/favicon.ico')?>"/>
    </head>
    <body>
	<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Irish Cinemas</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="/cinema/booking/search">Home</a></li>
      <li><a href="/cinema/customer/search">Customer</a></li>
      <li><a href="/cinema/Booking/search">Booking</a></li>
      <li><a href="/cinema/screen/search">Screen</a></li>
    </ul>
<form class="navbar-form navbar-left" action="/cinema/screen/search">
	<div class="input-group">
		<input type="text" class="form-control" placeholder="Search">
		<div class="input-group-btn">
		<button class="btn btn-default" type="submit">
        <i class="glyphicon glyphicon-search"></i>
      </button>
    </div>
  </div>
</form>
  </div>
</nav>
        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
        <!-- Latest compiled and minified JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
		<div class="container">
            <?php echo $this->getContent(); ?>
        </div>
    </body>
</html>